### ISSUE TITLE
Enter and view bank account balance

### ISSUE THREAD

**Issue by JohannaHopp** [JohannaHopp/capstone-project#1]
## Value Proposition

**As a** user
**I need** to enter my name and bank account balance
**to be able to** check how much money I have.

## Description

![Image](https://user-images.githubusercontent.com/112806881/201674040-c816189c-693d-43b5-8630-ee4fb1dc1fbf.png)

## Acceptance Criteria

- [x] the user welcome and App name is displayed
- [x] form with required input field for name
- [ ] form with required input field for bank account balance
- [ ] after submit the input of the name and account balance from the form is shown below on the same page

## Tasks

- [ ] make sure that only numbers can be entered in the bank account balance input
- [ ] create button component
- [ ] use onSubmit
- [ ] after submit the input values should be displayed below the form as a list
