### ISSUE TITLE
Add options page

### ISSUE THREAD

**Issue by JohannaHopp** [JohannaHopp/capstone-project#3]
## Value Proposition

**As a** user
**I need** the option to change my name or account status
**to be able to** correct it in case I made a mistake when entering it or want to delete everything

## Description

![Image](https://user-images.githubusercontent.com/112806881/202125022-f6248d76-80b0-4629-bf79-2779296b05b6.png)

## Acceptance Criteria

- [ ] a options-button to open a new page that shows the options
- [ ] form with name input to change the name
- [ ] form with bank account status input to change the number
- [ ] submit button for name 
- [ ] submit button for bank account change

## Tasks

- [ ] button on landing page to go to options
- [ ] create new page for options
- [ ] create form element to change the user name
- [ ] create form element for bank account balance change
- [ ] make sure that only numbers can be entered in the bank account balance input
- [ ] create button component
        - [ ] button for name change
        - [ ] button for bank account status change
- [ ] use onSubmit
- [ ] button that deletes everthing and brings you back to the start

**Comment by ahohnsen** [comment]
Hey Johanna,

I have a few suggestions/comments:

Description:
As far as I remember, we said that the data, the user entered in the form, should be displayed on the overview page (reminder: "Zahlungsverlauf"). So that the user can see what he/she entered. Please adjust the wireframe and acceptance criteria accordingly.

Acceptance Criteria:

> -after clicking the button a form will be displayed
Maybe you can be a bit more specific here, so it is more clear if the user will be redirected to another page with the form or if a modal with a form will open on button click.


> -after pressing the confirm button, the user is returned to the overview page and
> the amount entered was deducted from the account balance
Here you can add that the entered expense will be displayed on the overview page in a list.

- Additionally, you should mention, what happens if the user clicks on the button "abbrechen und zurück".
