### ISSUE TITLE
Delete option

### ISSUE THREAD

**Issue by JohannaHopp** [JohannaHopp/capstone-project#5]
## Value Proposition

**As a** user
**I need** the option to delete everything
**to be able to** delete my data if I no longer want to use the app

## Description

![Image](https://user-images.githubusercontent.com/112806881/203024679-cc1d0139-f7e1-4bd8-85d7-17576cfbf729.png)

## Acceptance Criteria

- [ ] on the options-page is a delete-button in the lower right corner
- [ ] after clicking the delete button a pop up appears asking the user if he really wants to delete everything
- [ ] if the user clicks at delete everything, he/she will be taken back to the start page
- [ ] if the user clicks at the "cancel-and-back"-button, he/she comes back to the options page

## Tasks

- [ ] button on the options page in the lower right corner
- [ ] pop up that ask the user if he/she really wants to delete everything
- [ ] button on the pop up that brings the user back to the options page
- [ ] button on the pop up that deletes everything
- [ ] delete button should bring the user back to the beginning of the app

**Comment by ahohnsen** [comment]
Hey Johanna,

In your previous user story you have added the "-" button, so as that one already exists, it should be in your wireframes :) 
Otherwise, please have a look at my comments in your previous user story - same applies here 👀
