### ISSUE TITLE
payment history page

### ISSUE THREAD

**Issue by JohannaHopp** [JohannaHopp/capstone-project#8]
## Value Proposition

**As a** user
**I need** to see the payment history on an extra page
**to be able to** keep an orderly and clear overview

## Description

![Image](https://user-images.githubusercontent.com/112806881/204325236-df6fef1f-87ab-44b6-977c-ce9239dc9804.png)

## Acceptance Criteria

- [ ] a link that called "Zahlungsverlauf" at the overview page
- [ ] after clicking the link, the user gets to a new page
- [ ] the new page displays a list with the payment history
- [ ] a link called "zurück" brings the user back to the overview page

## Tasks

- [ ] a link styled as a button displayed "Zahlungsverlauf", that brings the user to a new page
- [ ] a new page for payment history
- [ ] a list with all adds and amount
- [ ] link styled as a button and go back to overview page
