### ISSUE TITLE
options page

### ISSUE THREAD

**Issue by JohannaHopp** [JohannaHopp/capstone-project#9]
## Value Proposition

**As a** user
**I need** the option to change my name and/or account status
**to be able to** correct it in case I made mistakes when entering it 

## Description

![Image](https://user-images.githubusercontent.com/112806881/202201753-73fb2c21-35f9-4808-aa78-b921bd403823.png)

## Acceptance Criteria

- [ ] clicking the options-button at the overview page opens a new page where the options are displayed
- [ ] on the options-page:
> - [ ] there is a form with input fields for name and bank account status
> - [ ] the input fields are prefilled with the users data
> - [ ] by clicking the submit button , the user submits the changes and gets redirected back to the overview page
> - [ ] a button that leads back to the overview page after clicking

## Tasks

- [ ] button on overview page to go to options
- [ ] create new page for options
- [ ] create form element to change the user name and bank account balance
- [ ] the input fields are prefilled with the users data
- [ ] make sure that only numbers can be entered in the bank account balance input
- [ ] create button component
- [ ] button that is called "ändern" for name and bank account status change
- [ ] use onSubmit
- [ ] button that leads back to the overview page
